version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build: .
    #command: rails server -p 4000 -b '0.0.0.0'
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db